#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <string>

#include <pyc/cpp/pyc_konata.hpp>
#include <pyc/cpp/pyc_tb.hpp>

// Generated by `pyc-compile --emit=cpp`.
#include "janus_bcc_pyc_gen.hpp"

using pyc::cpp::Testbench;
using pyc::cpp::Wire;

namespace {

constexpr std::uint64_t kBootPc = 0x0000'0000'0001'0000ull;
constexpr std::uint64_t kBootSp = 0x0000'0000'0002'0000ull;

static bool envFlag(const char *name) {
  const char *v = std::getenv(name);
  if (!v)
    return false;
  // Treat explicit "0" as disabled to support script defaults like PYC_KONATA=${PYC_KONATA:-1}.
  return !(v[0] == '0' && v[1] == '\0');
}

static const char *stageName(std::uint64_t st) {
  switch (st) {
  case 0: // ST_IF
    return "IF";
  case 1: // ST_ID
    return "ID";
  case 2: // ST_EX
    return "EX";
  case 3: // ST_MEM
    return "MEM";
  case 4: // ST_WB
    return "WB";
  default:
    return "ST?";
  }
}

template <unsigned AddrWidth, unsigned DataWidth, std::size_t DepthBytes>
static bool loadMemh(pyc::cpp::pyc_byte_mem<AddrWidth, DataWidth, DepthBytes> &mem, const std::string &path) {
  std::ifstream f(path);
  if (!f.is_open()) {
    std::cerr << "ERROR: failed to open memh: " << path << "\n";
    return false;
  }

  std::uint64_t addr = 0;
  std::string tok;
  while (f >> tok) {
    if (tok.empty())
      continue;
    if (tok[0] == '@') {
      addr = std::stoull(tok.substr(1), nullptr, 16);
      continue;
    }
    unsigned v = std::stoul(tok, nullptr, 16) & 0xFFu;
    mem.pokeByte(static_cast<std::size_t>(addr), static_cast<std::uint8_t>(v));
    addr++;
  }
  return true;
}

static bool runProgram(const char *name, const char *memhPath, std::uint64_t bootPc, std::optional<std::uint32_t> expectedMem100,
                       std::optional<std::uint64_t> expectedA0) {
  pyc::gen::janus_bcc_pyc dut{};
  if (!loadMemh(dut.mem, memhPath))
    return false;

  dut.boot_pc = Wire<64>(bootPc);
  dut.boot_sp = Wire<64>(kBootSp);

  Testbench<pyc::gen::janus_bcc_pyc> tb(dut);

  const bool trace_log = (std::getenv("PYC_TRACE") != nullptr);
  const bool trace_vcd = (std::getenv("PYC_VCD") != nullptr);
  const bool trace_konata = envFlag("PYC_KONATA");
  std::filesystem::path out_dir{};
  if (trace_log || trace_vcd || trace_konata) {
    const char *trace_dir_env = std::getenv("PYC_TRACE_DIR");
    out_dir = trace_dir_env ? std::filesystem::path(trace_dir_env) : std::filesystem::path("janus/generated/janus_bcc_pyc");
    std::filesystem::create_directories(out_dir);

    if (trace_log) {
      tb.enableLog((out_dir / (std::string("tb_janus_bcc_pyc_cpp_") + name + ".log")).string());
      tb.log() << "tb_janus_bcc_pyc(C++): memh=" << memhPath << " boot_pc=0x" << std::hex << bootPc << std::dec << "\n";
    }

    if (trace_vcd) {
      tb.enableVcd((out_dir / (std::string("tb_janus_bcc_pyc_cpp_") + name + ".vcd")).string(), /*top=*/"tb_janus_bcc_pyc_cpp");
      tb.vcdTrace(dut.clk, "clk");
      tb.vcdTrace(dut.rst, "rst");
      tb.vcdTrace(dut.boot_pc, "boot_pc");
      tb.vcdTrace(dut.boot_sp, "boot_sp");
      tb.vcdTrace(dut.halted, "halted");
      tb.vcdTrace(dut.pc, "pc");
      tb.vcdTrace(dut.stage, "stage");
      tb.vcdTrace(dut.cycles, "cycles");
      tb.vcdTrace(dut.if_window, "if_window");
      tb.vcdTrace(dut.wb_op, "wb_op");
      tb.vcdTrace(dut.wb_regdst, "wb_regdst");
      tb.vcdTrace(dut.wb_value, "wb_value");
      tb.vcdTrace(dut.commit_cond, "commit_cond");
      tb.vcdTrace(dut.commit_tgt, "commit_tgt");
      tb.vcdTrace(dut.a0, "a0");
      tb.vcdTrace(dut.a1, "a1");
      tb.vcdTrace(dut.ra, "ra");
      tb.vcdTrace(dut.sp, "sp");
      tb.vcdTrace(dut.br_kind, "br_kind");
    }
  }

  tb.addClock(dut.clk, /*halfPeriodSteps=*/1);
  tb.reset(dut.rst, /*cyclesAsserted=*/2, /*cyclesDeasserted=*/1);

  pyc::cpp::KonataWriter konata{};
  if (trace_konata) {
    std::uint64_t start = dut.cycles.value();
    if (!konata.open(out_dir / (std::string("tb_janus_bcc_pyc_cpp_") + name + ".konata"), start)) {
      std::cerr << "WARN: failed to open konata trace output under " << out_dir << "\n";
    }
  }

  std::uint64_t insnCount = 0;

  struct PvState {
    bool valid = false;
    std::uint64_t pc = 0;
    std::uint64_t id = 0;
    std::uint64_t stage = 0;
  };
  PvState pv{};
  std::uint64_t pvNextId = 1;

  for (std::uint64_t i = 0; i < 200000; i++) {
    if (konata.isOpen())
      konata.atCycle(dut.cycles.value());

    if (konata.isOpen()) {
      const bool halted = dut.halted.toBool();
      const std::uint64_t pc = dut.pc.value();
      const std::uint64_t st = dut.stage.value();

      const bool newInsn = (!pv.valid) || (pc != pv.pc);
      if (halted) {
        if (pv.valid) {
          konata.stageEnd(pv.id, /*laneId=*/0, stageName(pv.stage));
          konata.retire(pv.id, /*retireId=*/pv.id, /*type=*/0);
          pv.valid = false;
        }
      } else if (newInsn) {
        if (pv.valid) {
          konata.stageEnd(pv.id, /*laneId=*/0, stageName(pv.stage));
          konata.retire(pv.id, /*retireId=*/pv.id, /*type=*/0);
        }
        pv.valid = true;
        pv.pc = pc;
        pv.id = pvNextId++;
        pv.stage = st;
        konata.insn(/*fileId=*/pv.id, /*simId=*/pc, /*threadId=*/0);
        std::ostringstream ss;
        ss << "pc=0x" << std::hex << pc;
        konata.label(pv.id, /*type=*/0, ss.str());
        konata.stageStart(pv.id, /*laneId=*/0, stageName(st));
      } else if (st != pv.stage) {
        konata.stageEnd(pv.id, /*laneId=*/0, stageName(pv.stage));
        pv.stage = st;
        konata.stageStart(pv.id, /*laneId=*/0, stageName(st));
      }
    }

    if (trace_log && dut.stage.value() == 4 && !dut.halted.toBool()) { // ST_WB
      insnCount++;
      tb.log() << "[wb #" << std::dec << insnCount << "] pc=0x" << std::hex << dut.pc.value()
               << " win=0x" << dut.if_window.value() << " op=" << std::dec << dut.wb_op.value()
               << " regdst=" << dut.wb_regdst.value() << " value=0x" << std::hex << dut.wb_value.value()
               << " a0=0x" << dut.a0.value() << " a1=0x" << dut.a1.value() << " ra=0x" << dut.ra.value()
               << " sp=0x" << dut.sp.value() << " br_kind=" << std::dec << dut.br_kind.value()
               << " commit_cond=" << dut.commit_cond.value() << " commit_tgt=0x" << std::hex << dut.commit_tgt.value()
               << std::dec << "\n";
    }
    tb.runCycles(1);
    if (dut.halted.toBool())
      break;
  }
  if (!dut.halted.toBool()) {
    std::cerr << "FAIL " << name << ": did not halt (pc=0x" << std::hex << dut.pc.value() << ")\n";
    return false;
  }

  if (expectedA0.has_value()) {
    std::uint64_t got = dut.a0.value();
    if (got != *expectedA0) {
      std::cerr << "FAIL " << name << ": a0=0x" << std::hex << got << " expected 0x" << *expectedA0
                << " (pc=0x" << dut.pc.value() << " a1=0x" << dut.a1.value() << " ra=0x" << dut.ra.value()
                << " sp=0x" << dut.sp.value() << ")" << std::dec << "\n";
      return false;
    }
  }

  std::uint32_t got = dut.mem.peek32(0x100);
  if (expectedMem100.has_value()) {
    if (got != *expectedMem100) {
      std::cerr << "FAIL " << name << ": mem[0x100]=0x" << std::hex << got << " expected 0x" << *expectedMem100 << std::dec << "\n";
      return false;
    }
    std::cout << "ok: " << name << " (cycles=" << std::dec << dut.cycles.value() << ")\n";
  } else {
    std::cout << "ok: " << name << " (cycles=" << std::dec << dut.cycles.value() << " mem[0x100]=0x" << std::hex << got << std::dec << ")\n";
  }
  return true;
}

} // namespace

int main(int argc, char **argv) {
  if (argc >= 2) {
    const char *memh = argv[1];
    std::optional<std::uint32_t> expectedMem100{};
    std::optional<std::uint64_t> expectedA0{};
    if (argc >= 3)
      expectedMem100 = static_cast<std::uint32_t>(std::stoul(argv[2], nullptr, 0));
    if (argc >= 4)
      expectedA0 = static_cast<std::uint64_t>(std::stoull(argv[3], nullptr, 0));
    std::uint64_t bootPc = kBootPc;
    if (const char *env = std::getenv("PYC_BOOT_PC")) {
      bootPc = static_cast<std::uint64_t>(std::stoull(env, nullptr, 0));
    }
    return runProgram("program", memh, bootPc, expectedMem100, expectedA0) ? 0 : 1;
  }

  // Default regression tests (memh fixtures checked into this repo).
  if (!runProgram("test_csel_fixed", "janus/programs/test_csel_fixed.memh", kBootPc, /*expectedMem100=*/100u, /*expectedA0=*/{}))
    return 1;
  if (!runProgram("test_or", "janus/programs/test_or.memh", kBootPc, /*expectedMem100=*/0x0000FF00u, /*expectedA0=*/{}))
    return 1;

  if (!runProgram("test_branch2", "janus/programs/test_branch2.memh", /*bootPc=*/kBootPc + 0x0a, /*expectedMem100=*/{}, /*expectedA0=*/8u))
    return 1;
  if (!runProgram("test_call_simple", "janus/programs/test_call_simple.memh", /*bootPc=*/kBootPc + 0x1c, /*expectedMem100=*/{}, /*expectedA0=*/42u))
    return 1;
  if (!runProgram("test_jump", "janus/programs/test_jump.memh", kBootPc, /*expectedMem100=*/{}, /*expectedA0=*/42u))
    return 1;
  if (!runProgram("test_pcrel", "janus/programs/test_pcrel.memh", kBootPc, /*expectedMem100=*/{}, /*expectedA0=*/43u))
    return 1;
  return 0;
}
