#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <optional>
#include <string>

#include <pyc/cpp/pyc_tb.hpp>

// Generated by `pyc-compile --emit=cpp`.
#include "linx_cpu_pyc_gen.hpp"

using pyc::cpp::Testbench;
using pyc::cpp::Wire;

namespace {

constexpr std::uint64_t kBootPc = 0x0000'0000'0001'0000ull;
// Keep the default SP away from the default .data placement (elf_to_memh.py uses 0x20000).
constexpr std::uint64_t kBootSp = 0x0000'0000'000f'ff00ull;

template <unsigned AddrWidth, unsigned DataWidth, std::size_t DepthBytes>
static bool loadMemh(pyc::cpp::pyc_byte_mem<AddrWidth, DataWidth, DepthBytes> &mem, const std::string &path) {
  std::ifstream f(path);
  if (!f.is_open()) {
    std::cerr << "ERROR: failed to open memh: " << path << "\n";
    return false;
  }

  std::uint64_t addr = 0;
  std::string tok;
  while (f >> tok) {
    if (tok.empty())
      continue;
    if (tok[0] == '@') {
      addr = std::stoull(tok.substr(1), nullptr, 16);
      continue;
    }
    unsigned v = std::stoul(tok, nullptr, 16) & 0xFFu;
    mem.pokeByte(static_cast<std::size_t>(addr), static_cast<std::uint8_t>(v));
    addr++;
  }
  return true;
}

static bool runProgram(const char *name, const char *memhPath, std::uint64_t bootPc, std::optional<std::uint32_t> expectedMem100,
                       std::optional<std::uint64_t> expectedA0, std::optional<std::uint32_t> expectedExitCode = std::nullopt) {
  pyc::gen::linx_cpu_pyc dut{};
  if (!loadMemh(dut.imem, memhPath))
    return false;
  if (!loadMemh(dut.dmem, memhPath))
    return false;

  dut.boot_pc = Wire<64>(bootPc);
  std::uint64_t bootSp = kBootSp;
  if (const char *env = std::getenv("PYC_BOOT_SP")) {
    bootSp = static_cast<std::uint64_t>(std::stoull(env, nullptr, 0));
  }
  dut.boot_sp = Wire<64>(bootSp);
  dut.irq = Wire<1>(0);
  dut.irq_vector = Wire<64>(0);

  Testbench<pyc::gen::linx_cpu_pyc> tb(dut);

  const bool trace_log = (std::getenv("PYC_TRACE") != nullptr);
  const bool trace_vcd = (std::getenv("PYC_VCD") != nullptr);
  if (trace_log || trace_vcd) {
    const char *trace_dir_env = std::getenv("PYC_TRACE_DIR");
    std::filesystem::path out_dir =
        trace_dir_env ? std::filesystem::path(trace_dir_env) : std::filesystem::path("examples/generated/linx_cpu_pyc");
    std::filesystem::create_directories(out_dir);

    if (trace_log) {
      tb.enableLog((out_dir / (std::string("tb_linx_cpu_pyc_cpp_") + name + ".log")).string());
      tb.log() << "tb_linx_cpu_pyc(C++): memh=" << memhPath << " boot_pc=0x" << std::hex << bootPc << std::dec << "\n";
    }

    if (trace_vcd) {
      tb.enableVcd((out_dir / (std::string("tb_linx_cpu_pyc_cpp_") + name + ".vcd")).string(), /*top=*/"tb_linx_cpu_pyc_cpp");
      tb.vcdTrace(dut.clk, "clk");
      tb.vcdTrace(dut.rst, "rst");
      tb.vcdTrace(dut.boot_pc, "boot_pc");
      tb.vcdTrace(dut.boot_sp, "boot_sp");
      tb.vcdTrace(dut.irq, "irq");
      tb.vcdTrace(dut.irq_vector, "irq_vector");
      tb.vcdTrace(dut.halted, "halted");
      tb.vcdTrace(dut.exit_code, "exit_code");
      tb.vcdTrace(dut.uart_valid, "uart_valid");
      tb.vcdTrace(dut.uart_byte, "uart_byte");
      tb.vcdTrace(dut.pc, "pc");
      tb.vcdTrace(dut.stage, "stage");
      tb.vcdTrace(dut.cycles, "cycles");
      tb.vcdTrace(dut.if_window, "if_window");
      tb.vcdTrace(dut.wb0_valid, "wb0_valid");
      tb.vcdTrace(dut.wb1_valid, "wb1_valid");
      tb.vcdTrace(dut.wb0_pc, "wb0_pc");
      tb.vcdTrace(dut.wb1_pc, "wb1_pc");
      tb.vcdTrace(dut.wb0_op, "wb0_op");
      tb.vcdTrace(dut.wb1_op, "wb1_op");
      tb.vcdTrace(dut.wb_op, "wb_op");
      tb.vcdTrace(dut.wb_regdst, "wb_regdst");
      tb.vcdTrace(dut.wb_value, "wb_value");
      tb.vcdTrace(dut.commit_cond, "commit_cond");
      tb.vcdTrace(dut.commit_tgt, "commit_tgt");
      tb.vcdTrace(dut.a0, "a0");
      tb.vcdTrace(dut.a1, "a1");
      tb.vcdTrace(dut.ra, "ra");
      tb.vcdTrace(dut.sp, "sp");
    }
  }

  tb.addClock(dut.clk, /*halfPeriodSteps=*/1);
  tb.reset(dut.rst, /*cyclesAsserted=*/2, /*cyclesDeasserted=*/1);

  std::uint64_t insnCount = 0;
  std::uint64_t maxCycles = 200000;
  if (const char *env = std::getenv("PYC_MAX_CYCLES")) {
    maxCycles = static_cast<std::uint64_t>(std::stoull(env, nullptr, 0));
  }

  for (std::uint64_t i = 0; i < maxCycles; i++) {
    if (dut.uart_valid.toBool()) {
      const char c = static_cast<char>(dut.uart_byte.value() & 0xFFu);
      if (trace_log) {
        tb.log() << c;
      }
      std::cout << c << std::flush;
    }
    if (trace_log && dut.stage.value() == 4 && !dut.halted.toBool()) { // ST_WB
      insnCount++;
      tb.log() << "[wb #" << std::dec << insnCount << "] pc=0x" << std::hex << dut.pc.value()
               << " win=0x" << dut.if_window.value() << " op=" << std::dec << dut.wb_op.value()
               << " regdst=" << dut.wb_regdst.value() << " value=0x" << std::hex << dut.wb_value.value()
               << " a0=0x" << dut.a0.value() << " a1=0x" << dut.a1.value() << " ra=0x" << dut.ra.value()
               << " sp=0x" << dut.sp.value() << " br_kind=" << std::dec << dut.br_kind.value()
               << " commit_cond=" << dut.commit_cond.value() << " commit_tgt=0x" << std::hex << dut.commit_tgt.value()
               << std::dec << "\n";
    }
    tb.runCycles(1);
    if (dut.halted.toBool())
      break;
  }
  if (!dut.halted.toBool()) {
    std::cerr << "FAIL " << name << ": did not halt after " << std::dec << maxCycles << " cycles (pc=0x" << std::hex
              << dut.pc.value() << ")\n";
    return false;
  }

  const bool haltedInvalid =
      (dut.wb0_valid.toBool() && dut.wb0_op.value() == 0) || (dut.wb1_valid.toBool() && dut.wb1_op.value() == 0);
  if (haltedInvalid) {
    std::cerr << "FAIL " << name << ": halted due to OP_INVALID"
              << " (wb0: valid=" << dut.wb0_valid.toBool() << " pc=0x" << std::hex << dut.wb0_pc.value()
              << " op=" << std::dec << dut.wb0_op.value() << ", wb1: valid=" << dut.wb1_valid.toBool()
              << " pc=0x" << std::hex << dut.wb1_pc.value() << " op=" << std::dec << dut.wb1_op.value()
              << ")\n";
    return false;
  }

  if (expectedExitCode.has_value()) {
    std::uint32_t got = static_cast<std::uint32_t>(dut.exit_code.value());
    if (got != *expectedExitCode) {
      std::cerr << "FAIL " << name << ": exit_code=0x" << std::hex << got << " expected 0x" << *expectedExitCode
                << std::dec << "\n";
      return false;
    }
  }

  if (expectedA0.has_value()) {
    std::uint64_t got = dut.a0.value();
    if (got != *expectedA0) {
      std::uint32_t mem0 = dut.dmem.peek32(0x0);
      std::uint32_t mem20000 = dut.dmem.peek32(0x20000);
      std::cerr << "FAIL " << name << ": a0=0x" << std::hex << got << " expected 0x" << *expectedA0
                << " (pc=0x" << dut.pc.value() << " a1=0x" << dut.a1.value() << " ra=0x" << dut.ra.value()
                 << " sp=0x" << dut.sp.value() << " mem[0]=0x" << mem0 << " mem[0x20000]=0x" << mem20000 << ")"
                << std::dec << "\n";
      return false;
    }
  }

  std::uint32_t got = dut.dmem.peek32(0x100);
  if (expectedMem100.has_value()) {
    if (got != *expectedMem100) {
      std::cerr << "FAIL " << name << ": mem[0x100]=0x" << std::hex << got << " expected 0x" << *expectedMem100
                << std::dec << "\n";
      return false;
    }
    std::cout << "ok: " << name << " (cycles=" << std::dec << dut.cycles.value() << ")\n";
  } else {
    std::cout << "ok: " << name << " (cycles=" << std::dec << dut.cycles.value() << " mem[0x100]=0x" << std::hex << got
              << std::dec << ")\n";
  }
  return true;
}

} // namespace

int main(int argc, char **argv) {
  if (argc >= 2) {
    const char *memh = argv[1];
    std::optional<std::uint32_t> expectedMem100{};
    std::optional<std::uint64_t> expectedA0{};
    if (argc >= 3)
      expectedMem100 = static_cast<std::uint32_t>(std::stoul(argv[2], nullptr, 0));
    if (argc >= 4)
      expectedA0 = static_cast<std::uint64_t>(std::stoull(argv[3], nullptr, 0));
    std::uint64_t bootPc = kBootPc;
    if (const char *env = std::getenv("PYC_BOOT_PC")) {
      bootPc = static_cast<std::uint64_t>(std::stoull(env, nullptr, 0));
    }
    std::optional<std::uint32_t> expectedExit{};
    if (const char *env = std::getenv("PYC_EXPECT_EXIT")) {
      expectedExit = static_cast<std::uint32_t>(std::stoul(env, nullptr, 0));
    }
    return runProgram("program", memh, bootPc, expectedMem100, expectedA0, expectedExit) ? 0 : 1;
  }

  // Default regression tests (memh fixtures checked into the repo).
  if (!runProgram("test_csel_fixed", "examples/linx_cpu/programs/test_csel_fixed.memh", kBootPc, /*expectedMem100=*/100u, /*expectedA0=*/{}))
    return 1;
  if (!runProgram("test_or", "examples/linx_cpu/programs/test_or.memh", kBootPc, /*expectedMem100=*/0x0000FF00u, /*expectedA0=*/{}))
    return 1;

  if (!runProgram("test_branch2", "examples/linx_cpu/programs/test_branch2.memh", /*bootPc=*/kBootPc + 0x0a, /*expectedMem100=*/{}, /*expectedA0=*/8u))
    return 1;
  if (!runProgram("test_call_simple", "examples/linx_cpu/programs/test_call_simple.memh", /*bootPc=*/kBootPc + 0x1c, /*expectedMem100=*/{}, /*expectedA0=*/42u))
    return 1;
  if (!runProgram("test_jump", "examples/linx_cpu/programs/test_jump.memh", kBootPc, /*expectedMem100=*/{}, /*expectedA0=*/42u))
    return 1;
  if (!runProgram("test_pcrel", "examples/linx_cpu/programs/test_pcrel.memh", kBootPc, /*expectedMem100=*/{}, /*expectedA0=*/43u))
    return 1;
  return 0;
}
